- README.md
smae as above --> same as above
> Fix one char spelling mistake

- req.go
- resp.go
Progress now seems to report at a 200ms interval. If the file upload/download finishes before next 200ms, the finishing progress (100%) won't be reported.
This should fix the problem.
> Report progress on upload and download finish

- req.go
- resp.go
- setting.go
Currently, the reporting interval is hardcoded to 200ms. It would be best if the user can customize this reporting interval to suit their needs (e.g. transmitting the progress via resource-constrained networks etc.)
This commit adds an unexported field `progressInterval` to struct `Req` and propagating this field to other related places, i.e. `multipartHelper` struct for `UploadProgress` and in `resp.go` for `DownloadProgress`. This field can be set with function `SetProgressInterval`.
This is a non-breaking change, user updating to this version will not break their code or modify their current behavior since the default timeout has been set to the original value of 200ms on the default client.
At the time of writing this PR, I realized I haven't considered the fact that user might …
> Allow customization of progress reporting interval

- README.md
> fix: short variable declaration error

- header.go
- req.go
req库调用`req.Header.Add(key, value)`设置请求头，内部会调用`http.Header.Add`函数，该函数会把传入的key转成驼峰形式，该PR提供`ReservedHeader`，可以绕过默认实现，解决非标准的需求。
> feat: add ReservedHeader

- README.md
There is an error in the README, section **Basic Auth and Bearer Token** . SetCommonBearerToken method doesn't exit.
I've update SetCommonBearerToken  to SetCommonBearerAuthToken :  
```
// Set bearer token for all request
client.SetCommonBearerAuthToken("MDc0ZTg5YmU4Yzc5MjAzZGJjM2ZiMzkz")
````
> Update SetCommonBearerToken to SetCommonBearerAuthToken in the wiki

- request.go
A very similar function to SetQueryParam, but allowing multiple query params of the same name to be set.
Use case currently, before this change, using the HubSpot API
```go
r := client.R()
r.QueryParams.Add("properties", "budget")
r.QueryParams.Add("properties", "quantity")
r.QueryParams.Add("properties", "project_name")
r.QueryParams.Add("properties", "smg_company")
r.QueryParams.Add("properties", "date_needed")
r.QueryParams.Add("properties", "file_uploads")
r.QueryParams.Add("properties", "description")
r.QueryParams.Add("properties", "project_size")
r.QueryParams.Add("properties", "product_type")
r.QueryParams.Add("associations", "contacts")
r.QueryParams.Add("associations", "companies")
r, err := hubspot.Get(c, r, fmt.Sprintf("/crm/v3/objects/deals/%d", e.Event.ObjectID))
```
Which …
> `AddQueryParam` func on Request

- client.go
- retry_test.go
> fix miss executing ResponseMiddlewares

- request.go
- request_test.go
解决了中的问题，https://github.com/imroc/req/issues/112 。在不修改原来的基础上，增加三个方法，分别是`SetHeadersMap`，`SetHeaderMap`和`SetHeaderMaps`，均已经通过测试。
> To use non-canonical keys, assign to the map directly.

- trace.go
> Fix a syntax error in a map key

- client.go
- middleware.go
- retry_test.go
Reproduce:
1. `SetCommonRetryCondition`
```go
func retryCondition(resp *req.Response, err error) bool {
return false
}
```
2. Initiate a request after a network error (such as a disconnection)
> Fix potential null pointer issue when retrying with request

- request.go
- retry_test.go
Docs states that infinite retry happens when RetryCount is negative  (see: https://pkg.go.dev/github.com/imroc/req/v3#Client.SetCommonRetryCount), but actually it also happens for RetryCount eq zero.
As a result setting any `retryOption` using either Client or Request results in infinite retry, unless RetryCount is greater than 0.
This PR fixes it.
> fix: do not retry when RetryCount eq 0

- client.go
The self-signed cert will not work correctly if we don't set `RootCAs` in `utls.Config`.
> Fix RootCAs setting when using utls

- request.go
if resp.Err has been set, wont overwrite it
> allow RetryCondition and RetryHook wrap  the original error

- transport.go
It's lock protected and not safe for concurrent use.
It should use previously read context.
Otherwise, can panic under high concurrency.
> fix: use correct context for dial

- logger.go
- logger_test.go
You could not create a req.Logger from a log.Logger. Instead, you have to create one from an io.Writer.
Unfortunately, there are situations when you do not have access to the underlying io.Writer for your .Logger. This limits your ability to set the client logger using the tooling of your choice. 
You can usually convert your <whatever>.Logger into a log.Logger. With this PR, you're now able to create a req.Logger from a log.Logger and set your client logger as needed.
> Allow logger creation from an existing standard logger

- header.go
replaced value should be trimmed, otherwise escape characters won't be handled correctly.
> fix: header cleanup

- client.go
- client_impersonate.go
- client_test.go
- client_wrapper.go
- middleware.go
- response.go
req currently relies on Go's [`mime/multipart`](https://pkg.go.dev/mime/multipart@go1.23.2) package to generate unique boundary delimiters for `multipart/form-data` requests. The boundary delimiters generated by `mime/multipart` are made up of exactly 60 randomly-generated characters (numbers from 0-9 and lower-case letters from a-f only), e.g. `b26dc610159ba676929ced239b36e90370976ad0fc20a615e29e799608d2` (see [implementation](https://cs.opensource.google/go/go/+/refs/tags/go1.23.2:src/mime/multipart/writer.go;drc=b0b1d42db32a992150dd26681d3bda222e108303;l=84)).
All modern browsers use boundary delimiter formats different from those used by `mime/multipart`:
- Blink-based browsers (Chrome, Chromium, Edge, etc.) and WebKit-based browsers (Safari, etc.) generate boundary delimiters in the …
> Add client.SetMultipartBoundaryFunc and port Blink/WebKit/Firefox implementations

- client.go
- client_test.go
- redirect.go
There's currently no easy and intuitive way to change a client's redirect policy back to the default redirect policy.
For example: Let's say someone wants to send a `GET` request to a given URL, but is only interested in the `Location` header and the cookies of the response. They can use `c.SetRedirectPolicy(req.NoRedirectPolicy())` to disable redirects and manually grab the `Location` header, but there's no simple way to "reset" the redirect policy back to the default one.
They could go through req's source code until they find the following function, only to realize that they can achieve the same thing by setting the redirect policy to `req.MaxRedirectPolicy(10)`:
https://github.com/imroc/req/blob/24b0c84d2d4dac890b39f1d9a9ca494ac2f9a6d5/client.go#L324-L332
This PR introduces …
> Add DefaultRedirectPolicy

- response.go
在使用中间件对响应体进行加密/解密处理时，直接修改 Response.Body
无法生效，因为 body 已被读取到内存中。新增这两个方法可以直接
设置解密后的内容到 body 字段，确保后续获取响应内容时
能正确获取到解密后的数据。
- 添加 SetBody 方法用于设置字节数组形式的响应体
- 添加 SetBodyStr 方法用于设置字符串形式的响应体
相关场景:
- 响应体加密/解密中间件
- 响应内容统一处理
> feat(response): 添加 SetBody 和 SetBodyStr 方法

- client_impersonate.go
Commit fb51d5b changed the `client.ImpersonateXXX` methods to always use the latest TLS fingerprint provided by uTLS for the relevant browser (`utls.HelloXXX_Auto`). Unfortunately this creates a mismatch between the TLS fingerprint and the other browser settings (such as `User-Agent` headers) since the latter are not changed automatically with every uTLS version upgrade. It's quite easy for bot detection tools to detect this mismatch, with a pretty low chance of false positives. I suggest sticking with fixed version TLS fingerprints instead and manually updating the `uTLS.ClientHelloId` alongside other browser settings whenever new uTLS fingerprints become available.
I've used Chrome 120, Firefox 120 and Safari 16.6 on a fresh MacOS 13 installation to check for relevant `commonHeaders` …
> Update client.ImpersonateXXX methods

- request.go
- trace.go
TraceInfo struct contains both RemoteAddr and LocalAddr, which makes a tcp connection tuple
> feat: Add LocalAddr to TraceInfo to capture local network address
